-- =====================================================================
-- 02_functions.sql
-- Funciones de soporte de los triggers viven en 03_triggers.sql, junto a su
-- trigger. Este archivo es para funciones de propósito general sin trigger.
-- =====================================================================
